### ISSUE TITLE
邮件发送一直没有成功

### ISSUE THREAD

**Issue by hack2012** [zj1244/beholder_web#2]
邮件发送是不是有bug？

**Comment by zj1244** [comment]
> 邮件发送是不是有bug？

你的发件服务器和收件服务器分别是哪个？qq？163？

**Comment by hack2012** [comment]
我测试过qq，outlook都没有成功，163的还没有试

**Comment by hack2012** [comment]
又测试了新浪邮箱的，居然可以。 多谢

**Comment by zj1244** [comment]
> 又测试了新浪邮箱的，居然可以。 多谢


哈哈，我测试了qq也是可以的，你看是不是被当成垃圾邮件了。还有freebuf回你私信了
![image](https://user-images.githubusercontent.com/29372171/91003292-7b87a900-e603-11ea-9408-927834214949.png)

**Comment by hack2012** [comment]
阿里云企业邮箱和outlook邮箱测试了，死活通不过，不知道为什么。
QQ邮箱：使用同一账号的xxx@qq.com成功，xxx@vip.qq.com不成功。

**Comment by zj1244** [comment]
> 阿里云企业邮箱和outlook邮箱测试了，死活通不过，不知道为什么。
> QQ邮箱：使用同一账号的[xxx@qq.com](mailto:xxx@qq.com)成功，[xxx@vip.qq.com](mailto:xxx@vip.qq.com)不成功。

阿里云企业邮箱现在可以发送了。outlook因加密方式就先不支持了。vip.qq.com没有账号没法测试暂时先不弄了
issue:fix by commit c6570e1
