### ISSUE TITLE
无法删除任务

### ISSUE THREAD

**Issue by hack2012** [zj1244/beholder_web#3]
![1](https://user-images.githubusercontent.com/3817100/91011602-2eadcd80-e617-11ea-9d6f-f9d67245160d.png)
建了个循环任务，点击删除以后，chrome控制台报这个错误。
Chrome版本 84.0.4147.135（正式版本） （64 位）
Mac 10.15.6

**Comment by zj1244** [comment]
我测试了没有问题。Chrome版本 84+win7
![x](https://user-images.githubusercontent.com/29372171/91016754-d8915800-e61f-11ea-99a0-5cda01d29723.gif)

**Comment by hack2012** [comment]
经过多次测试发现，可能是Tampermonkey中的百度谷歌去广告脚本导致的，再次感谢作者。
![1](https://user-images.githubusercontent.com/3817100/91028881-ab997100-e630-11ea-9ea5-8e41328db7e7.png)

**Comment by zj1244** [comment]
客气了，有用的话可以点个Star支持一下:smiley:
